FROM mcr.microsoft.com/dotnet/aspnet:6.0-focal AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:6.0-focal AS build
WORKDIR /src
COPY ["QLS.Api/QLS.Api.csproj", "QLS.Api/"]
COPY ["QLS.Application/QLS.Application.csproj", "QLS.Application/"]
COPY ["QLS.Domain/QLS.Domain.csproj", "QLS.Domain/"]
COPY ["QLS.Infrastructure/QLS.Infrastructure.csproj", "QLS.Infrastructure/"]
RUN dotnet restore "QLS.Api/QLS.Api.csproj"
COPY . .
WORKDIR "/src/QLS.Api"
RUN dotnet build "QLS.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "QLS.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "QLS.Api.dll"]